class CreateAppointments < ActiveRecord::Migration[8.1]
  def change
    create_table :appointments do |t|
      t.references :patient, null: false, foreign_key: true, index: false
      t.references :doctor, null: false, foreign_key: true, index: false
      t.references :availability, null: false, foreign_key: true, index: false

      # Times are copied from the availability at booking time. Editing the slot
      # afterwards must not silently move an appointment a patient already agreed to.
      t.datetime :starts_at, null: false
      t.datetime :ends_at, null: false

      t.string :status, null: false, default: "scheduled"
      t.datetime :cancelled_at
      t.string :cancellation_reason

      # The key the billing service knows this appointment by. Generated by PostgreSQL
      # from the primary key, so it can never drift from the row or be set by hand.
      t.virtual :external_ref, type: :string, as: "'appointment:' || id", stored: true

      t.timestamps
    end

    add_index :appointments, %i[doctor_id starts_at ends_at]
    add_index :appointments, %i[patient_id starts_at]
    add_index :appointments, %i[status starts_at]
    add_index :appointments, :external_ref, unique: true

    # The database half of the double-booking defence. The pessimistic lock in
    # Appointments::Book serialises the readers; this index is what makes the
    # invariant true even if a future code path forgets to take that lock.
    add_index :appointments, :availability_id,
              unique: true,
              where: "status IN ('scheduled', 'confirmed')",
              name: "index_appointments_on_active_availability"

    add_check_constraint :appointments, "ends_at > starts_at", name: "appointments_time_order_check"
    add_check_constraint :appointments,
                         "status IN ('scheduled', 'confirmed', 'completed', 'cancelled')",
                         name: "appointments_status_check"
  end
end
